# This file was generated by GoReleaser. DO NOT EDIT.
cask "spire" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "f445f4989e0b2c4963201a39582d38001153e914eb343547762fc803263e8d64"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5973f8322e4fd64b5a67747260db872c56c52887eaae66974babc7d30d71aa61"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f49645f20f951c298daa37ec28010103c53a78b4a46ef1227b177216b1bff882"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c092a78fc82d6adfaeed8b738b81bdb366b7b0034b647d72408437753e7c8646"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Linux_arm64.tar.gz"
    end
  end

  name "spire"
  desc "Scaffolding CLI that generates apps from versioned templates and keeps them in sync"
  homepage "https://github.com/schaemi85/spire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spire"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spire"]
    end
  end

  # No zap stanza required

end
