# This file was generated by GoReleaser. DO NOT EDIT.
cask "spire" do
  version "0.0.1-BETA"

  on_macos do
    on_intel do
      sha256 "2bf7220f7c135ebd75cdbde8eee8c3d3cc1d86145eef301fc570dfa448e32efd"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d9f4548ad016de5e4ed75fbae60a72a97a162434c9559739dc2833fc23c2ac1d"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b6f1d5ce161ddb3ef88f69cc61f24e74f2523edab2785d6fe9468c09f220dda2"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "680be6af98e592cfcf6bae2a7e69e9921fdb92fd45f77fdd9f6e8a9028e77264"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Linux_arm64.tar.gz"
    end
  end

  name "spire"
  desc "Scaffolding CLI that generates apps from versioned templates and keeps them in sync"
  homepage "https://github.com/schaemi85/spire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spire"]
    end
  end

  # No zap stanza required

end
