# This file was generated by GoReleaser. DO NOT EDIT.
cask "spire" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d9425b413c1d8b5d036e7b8876c59eefb1bc3a440f89df07e5eefd9a656a43de"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b662320c9dc34d3431c8423380bbda4a019d73e8603800e186c6855578b669e7"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d213484a6579074bc62b47ef7aa08428ccd1fdc6857e46fb3e147faf62c27704"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "057cb1c81026e3bba99b8b6bb4485b3c8942e7666b8b4a89ea8b23e227cf94a1"
      url "https://github.com/schaemi85/spire/releases/download/v#{version}/spire_Linux_arm64.tar.gz"
    end
  end

  name "spire"
  desc "Scaffolding CLI that generates apps from versioned templates and keeps them in sync"
  homepage "https://github.com/schaemi85/spire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spire"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spire"]
    end
  end

  # No zap stanza required

end
